apiVersion: v1
kind: Secret
metadata:
  # using same secret for both openshift-logging and netobserv
  #name: logging-loki-aws
  name: loki-s3
  # using same secret for both openshift-logging and netobserv
  #namespace: openshift-logging
  namespace: netobserv
type: Opaque
data:
  audience: b3BlbnNoaWZ0
  bucketnames: dGhlLWNsdXN0ZXItbG9raQ==
  region: YXAtc291dGhlYXN0LTI=
  role_arn: YXJuOmF3czppYW06Ojk3NTA1MDE5MjU0ODpyb2xlL3RoZS1jbHVzdGVyLWxva2lzdGFjay1hY2Nlc3Mtcm9sZQ==
