apiVersion: v1
kind: Secret
metadata:
  # using same secret for both openshift-logging and netobserv
  #name: logging-loki-aws
  name: loki-s3
  # using same secret for both openshift-logging and netobserv
  #namespace: openshift-logging
  namespace: netobserv
type: Opaque
data:
  audience: b64 "openshift"
  bucketnames: b64 "bucketname"
  region: b64 "region"
  role_arn: b64 "role arn"
