apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  #name: logging-loki 
  name: logging-network
  #namespace: openshift-logging
  namespace: netobserv
spec:
  size: 1x.extra-small 
  storage:
    schemas:
      - effectiveDate: '2023-10-15'
        version: v13
    secret:
      name: logging-loki-aws 
      type: s3 
      credentialMode: token
  storageClassName: gp3-csi
  tenants:
    #mode: openshift-logging
    mode: openshift-network
  limits:
    global:
      queries:
        maxQuerySeries: 2000
