apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  creationTimestamp: "2025-04-10T23:25:58Z"
  generation: 1
  labels:
    operators.coreos.com/loki-operator.openshift-operators-redhat: ""
  name: loki-operator
  namespace: openshift-operators-redhat
  resourceVersion: "2054082"
  uid: 06f82126-7df7-4bf8-9935-b8257a3af86a
spec:
  channel: stable-6.2
  config:
    env:
    - name: ROLEARN
      value: arn:aws:iam::975050192548:role/the-cluster-lokistack-access-role
  installPlanApproval: Manual
  name: loki-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: loki-operator.v6.2.0
