apiVersion: logging.openshift.io/v1alpha1
kind: LogFileMetricExporter
metadata:
  name: vector-metric-exporter
  namespace: openshift-logging
spec:
  resources:
    limits:
      cpu: 500m
    requests:
      cpu: 200m
      memory: 128Mi
