apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: openshift-logging-lokistack
  namespace: openshift-logging
spec:
  size: 1x.extra-small
  storage:
    schemas:
      - effectiveDate: '2023-10-15'
        version: v13
    secret:
      name: openshift-logging-lokistack
      type: s3
      credentialMode: token
  storageClassName: gp3-csi
  tenants:
    mode: openshift-logging
  limits:
    global:
      queries:
        maxQuerySeries: 2000
