apiVersion: v1
kind: Secret
metadata:
  name: openshift-logging-lokistack
  namespace: openshift-logging
type: Opaque
data:
  audience: b3BlbnNoaWZ0Cg==
  bucketnames: dGhlLWNsdXN0ZXItbG9raS1sb2dnaW5nCg==
  region: YXAtc291dGhlYXN0LTIK
  role_arn: YXJuOmF3czppYW06OjMxOTY2ODE4MzU4Mjpyb2xlL3RoZS1jbHVzdGVyLWxva2lzdGFjay1yb2xlCg==
