---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manager-rolebinding
roleRef:                                           
  apiGroup: rbac.authorization.k8s.io              
  kind: ClusterRole                                
  name: cluster-logging-operator                   
subjects:                                          
  - kind: ServiceAccount                           
    name: cluster-logging-operator                 
    namespace: openshift-logging  

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-logging-write-application-logs
roleRef:                                           
  apiGroup: rbac.authorization.k8s.io              
  kind: ClusterRole                                
  name: cluster-logging-write-application-logs     
subjects:                                          
  - kind: ServiceAccount                           
    name: logcollector
    namespace: openshift-logging  

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: collect-application-logs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: collect-application-logs
subjects:
- kind: ServiceAccount
  name: logcollector
  namespace: openshift-logging




---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-logging-write-audit-logs
roleRef:                                           
  apiGroup: rbac.authorization.k8s.io              
  kind: ClusterRole                                
  name: cluster-logging-write-audit-logs           
subjects:                                          
  - kind: ServiceAccount                           
    name: logcollector
    namespace: openshift-logging  

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-logging-write-infrastructure-logs
roleRef:                                           
  apiGroup: rbac.authorization.k8s.io              
  kind: ClusterRole                                
  name: cluster-logging-write-infrastructure-logs
subjects:                                          
  - kind: ServiceAccount                           
    name: logcollector
    namespace: openshift-logging  
