apiVersion: v1
kind: Secret
metadata:
  name: cloudwatch-credentials
  namespace: openshift-logging
stringData:
  credentials: |-
    [default]
    #sts_regional_endpoints = regional
    role_arn = arn:aws:iam::xxxxxxxxxxxxx:role/the-cluster-RosaCloudWatch
    #web_identity_token_file = /run/secrets/eks.amazonaws.com/serviceaccount/token
