apiVersion: v1
kind: Secret
metadata:
  name: cloudwatch-credentials
  namespace: openshift-logging
data:
  ## b64 role_arn
  credentials: YXJuOmF3czppYW06OjMxOTY2ODE4MzU4Mjpyb2xlL3RoZS1jbHVzdGVyLVJvc2FDbG91ZFdhdGNoCg==
