---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: FlowCollector.v1beta1.flows.netobserv.io,FlowCollector.v1beta2.flows.netobserv.io,FlowMetric.v1alpha1.flows.netobserv.io
  creationTimestamp: "2025-04-11T03:00:37Z"
  generateName: openshift-netobserv-operator-
  generation: 1
  name: openshift-netobserv-operator-7b77b
  namespace: openshift-netobserv-operator
  resourceVersion: "2114035"
  uid: 01349268-bdbe-419a-a074-ff71f78392fb
spec:
  upgradeStrategy: Default

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  creationTimestamp: "2025-04-11T03:00:37Z"
  generation: 1
  labels:
    operators.coreos.com/netobserv-operator.openshift-netobserv-operator: ""
  name: netobserv-operator
  namespace: openshift-netobserv-operator
  resourceVersion: "2114547"
  uid: 8512e1f7-7e96-4d57-aa95-200521b9ec45
spec:
  channel: stable
  installPlanApproval: Automatic
  name: netobserv-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: network-observability-operator.v1.8.0
