---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    capability.openshift.io/name: OperatorLifecycleManager
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    olm.providedAPIs: Alertmanager.v1.monitoring.coreos.com,PodMonitor.v1.monitoring.coreos.com,Probe.v1.monitoring.coreos.com,Prometheus.v1.monitoring.coreos.com,PrometheusRule.v1.monitoring.coreos.com,ServiceMonitor.v1.monitoring.coreos.com,ThanosRuler.v1.monitoring.coreos.com,AlertmanagerConfig.v1alpha1.monitoring.coreos.com
  name: openshift-cluster-monitoring
  namespace: openshift-monitoring
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    controller: true
    kind: ClusterVersion
    name: version
spec:
  selector:
    matchLabels:
      openshift.io/cluster-monitoring: "true"
  staticProvidedAPIs: true
  upgradeStrategy: Default

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  creationTimestamp: "2025-04-11T01:33:44Z"
  generation: 1
  labels:
    operators.coreos.com/cluster-observability-operator.openshift-cluster-observability: ""
  name: cluster-observability-operator
  namespace: openshift-cluster-observability-operator
  resourceVersion: "2089272"
  uid: 751cbab9-38cf-4e98-96c5-fef99b0a8e3f
spec:
  channel: stable
  installPlanApproval: Automatic
  name: cluster-observability-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: cluster-observability-operator.v1.1.0
